#配置elasticSearch集群的连接
spring:
  elasticsearch:
    rest:
      uris:
      - http://192.168.175.129:9200
      - http://192.168.175.130:9200
  #   uris: http://192.168.175.129:9200,http://192.168.175.130:9200 以上及这行两种方式都可以
  #配置数据库连接参数
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.129:3306/user?serverTimezone=CST&characterEncoding=utf-8
    username: root
    password: root